(in-package :cqlcl)


(defconstant +request+  #x01)
(defconstant +response+ #x81)
(defconstant +message-types+ (list +request+ +response+))
(defconstant +op-codes+
  (alexandria:alist-hash-table
   '((:error        . #x00)
     (:startup      . #x01)
     (:ready        . #x02)
     (:authenticate . #x03)
     (:credentials  . #x04)
     (:options      . #x05)
     (:supported    . #x06)
     (:query        . #x07)
     (:result       . #x08)
     (:prepare      . #x09)
     (:execute      . #x0a)
     (:register     . #x0b)
     (:event        . #x0c))))
(defconstant +consistency+
  (alexandria:alist-hash-table
   '((:any          . #x00)
     (:one          . #x01)
     (:two          . #x02)
     (:three        . #x03)
     (:quorum       . #x04)
     (:all          . #x05)
     (:local-quorum . #x06)
     (:each-quorum  . #x07))))

(defclass header ()
  ((ptype       :accessor ptype :initarg :ptype)
   (consistency :accessor cap   :initarg :cap)
   (stream-id   :accessor id    :initarg :id)
   (op-code     :accessor op    :initarg :op)
   (length      :accessor len   :initarg :len)))

(defmethod initialize-instance :after ((header header) &key)
  (when (not (integerp (gethash (op header) +op-codes+)))
    (error (format nil "Unknown op-code: ~A" (op header))))
  (when (not (integerp (gethash (cap header) +consistency+)))
    (error (format nil "Unknown consistency setting: ~A" (cap header))))
  (when (not (member (ptype header) +message-types+))
    (error (format nil "Unknown message type: ~A" (ptype header)))))
